services:
  dotanbooks-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: dotanbooks-api:latest
    container_name: dotanbooks-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      EnableHttpsRedirection: "false"
      ConnectionStrings__DefaultConnection: Server=sqlserver,1433;Database=DotanBooksDb;User Id=sa;Password=${DB_SA_PASSWORD};Encrypt=True;TrustServerCertificate=True
      Redis__Host: redis
      Redis__Port: "6379"
      Redis__Password: ${REDIS_PASSWORD}
      Redis__DefaultTtlSeconds: "120"
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: DotanBooks
      Jwt__Audience: DotanBooksUsers
      Cors__AllowedOrigins__0: http://localhost:4200
      Email__SmtpHost: smtp.gmail.com
      Email__SmtpPort: "587"
      Email__SenderName: Dotan Books
      Email__SenderAddress: ${EMAIL_SENDER_ADDRESS}
      Email__SenderPassword: ${EMAIL_SENDER_PASSWORD}
    depends_on:
      - sqlserver
      - redis

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dotanbooks-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${DB_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  redis:
    image: redis:7.2-alpine
    container_name: dotanbooks-redis
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  sqlserver_data:
  redis_data:
